version: '3.8'

services:
  rtsp-streamer:
    build: .
    container_name: esp32_rtsp_streamer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - RTSP_URL=rtsp://192.168.0.24/11
    tmpfs:
      - /tmp:exec,size=64M  # Монтуємо /tmp прямо у оперативну пам'ять (RAM), щоб не зношувати SSD/SD-карту!