services:
  rtsp-streamer:
    build: .
    container_name: esp32_rtsp_streamer
    restart: unless-stopped
    network_mode: "host"   # <--- Працює напряму через мережеву карту NAS, без буферів Docker
    environment:
      - RTSP_URL=rtsp://192.168.0.24/11
    tmpfs:
      - /tmp:exec,size=64M